name: Publish to PyPI

on:
    release:
        types: [created]

    # Allow manual triggering
    workflow_dispatch:
        inputs:
            target:
                description: 'Target PyPI repository'
                required: true
                default: 'test'
                type: choice
                options:
                    - test
                    - prod

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write # Required for trusted publishing
            contents: read # Required for checkout

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  version: 1.7.1
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v3
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root --without mlx

            - name: Install project
              run: poetry install --no-interaction --without mlx

            - name: Build package
              run: poetry build

            - name: Publish to Test PyPI
              if: inputs.target == 'test'
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/

            - name: Publish to PyPI
              if: inputs.target == 'prod'
              uses: pypa/gh-action-pypi-publish@release/v1
